name: core
tasks:
 core_unknown:
    description: Query doesn't fall into any of the other tasks
    steps:
      - utter: I don't know what you mean with that- Please try again! You can ask me what I can do!
 core_capabilities:
    name: Capabilities
    description: Inquiries what we can do or what capabilities we have
    steps:
      - utter: I can ~add numbers~ and show your ~advisor recommendations~ (sort of).
 add_numbers:
    name: Add numbers
    description: User wants to add 2 numbers
    steps:
      - utter: Ok, you want to add numbers. Please give me the first number.
      - collect: first_number
        name: First number
        type: number
      - utter: Good the first number is {{index .slots "first_number"}} now give me the second number.
      - collect: second_number
        name: Second number
        type: number
      - utter: The second number is {{index .slots "second_number"}}
      - action: add_numbers
 insights_advisor:
    name: Advisor recommendations
    description: Inquiries about advisor recommendations
    steps:
      - utter: So you want to see your advisor recommendations, is it for RHEL or OpenShift?
      - collect: advisor_system
        choices:
          - openshift
          - rhel
      - utter: Got it, you want to see advisor recommendations for {{index .slots "advisor_system"}}.
      - if: slots["advisor_system"] == "openshift"
        then:
          - utter: Here is your list of advisor recommendations for openshift
          - utter: Just kidding, I don't have that, bye!
        else:
          - utter: What kind of recommendations would you like to see?
          - collect: advisor_type
            choices:
              - performance
              - security
              - availability
              - stability
              - new
              - critical
              - workload
          - utter: Maybe someday i'll be able to show you {{index .slots "advisor_type"}} recommendations for advisor...
