name: core
tasks:
 core_unknown:
    description: Query doesn't fall into any of the other tasks
 core_capabilities:
    name: Capabilities
    description: Inquiries what we can do or what capabilities we have
    steps:
      - utter: I can ~add numbers~ and show your ~advisor recommendations~ (sort of).
 add_numbers:
    name: Add numbers
    description: User wants to add 2 numbers
    steps:
      - utter: Ok, you want to add numbers. Please give me the first number.
      - collect: first_number
        name: First number
        type: number
      - utter: Good, now give me the second number.
      - collect: second_number
        name: Second number
        type: number
      - action: add_numbers
 insights_advisor:
    name: Advisor recommendations
    description: Inquiries about advisor recommendations
    steps:
      - utter: Not implemented yet! I'll probably break now, have fun!
      - collect: advisor_system
        choices:
          - openshift
          - rhel
      - if: slots.advisor_system == "openshift"
        then:
          - action: advisor_openshift
          - next: END
        else:
          - collect: advisor_type
            choices:
              - performance
              - security
              - availability
              - stability
              - new
              - critical
              - workload
